// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"Galv_ScreenZoom","status":true,"description":"(v.1.1) Zoom in on a certain part of the screen","parameters":{"Battle Zoom":"1"}},
{"name":"CmdInp","status":true,"description":"v1.1.2 CmdInp Enables a Command Input system.","parameters":{"Text Variable":"1","Max Characters":"12","Use Image":"false","Image Name":"ClipComputer","Default Header":"\"This is a Input Window\"","Default InputText":"\"InputText\""}}
];
